import { prisma } from "@/lib/prisma";

const drinks = [
  {
    key: "Jugos con leche:Banana",
    name: "Banana",
    category: "Jugos con leche",
    tag: "500 / 700 ml",
    description: "Vaso 500ml Bs 25 · 700ml Bs 30. Con leche.",
    price: 25.0,
    colorway: "honey",
    imageUrl: "/images/drinks/jugos-con-leche-banana.jpg",
    isNew: false,
    sortOrder: 1,
  },
  {
    key: "Jugos con leche:Café",
    name: "Café",
    category: "Jugos con leche",
    tag: "500 / 700 ml",
    description: "Vaso 500ml Bs 25 · 700ml Bs 30. Con leche.",
    price: 25.0,
    colorway: "honey",
    imageUrl: "/images/drinks/jugos-con-leche-cafe.jpg",
    isNew: false,
    sortOrder: 2,
  },
  {
    key: "Jugos con leche:Caramelo",
    name: "Caramelo",
    category: "Jugos con leche",
    tag: "500 / 700 ml",
    description: "Vaso 500ml Bs 25 · 700ml Bs 30. Con leche.",
    price: 25.0,
    colorway: "honey",
    imageUrl: "/images/drinks/jugos-con-leche-caramelo.jpg",
    isNew: false,
    sortOrder: 3,
  },
  {
    key: "Jugos con leche:Coco",
    name: "Coco",
    category: "Jugos con leche",
    tag: "500 / 700 ml",
    description: "Vaso 500ml Bs 25 · 700ml Bs 30. Con leche.",
    price: 25.0,
    colorway: "honey",
    imageUrl: "/images/drinks/jugos-con-leche-coco.jpg",
    isNew: false,
    sortOrder: 4,
  },
  {
    key: "Jugos con leche:Chocolate",
    name: "Chocolate",
    category: "Jugos con leche",
    tag: "500 / 700 ml",
    description: "Vaso 500ml Bs 25 · 700ml Bs 30. Con leche.",
    price: 25.0,
    colorway: "honey",
    imageUrl: "/images/drinks/jugos-con-leche-chocolate.jpg",
    isNew: false,
    sortOrder: 5,
  },
  {
    key: "Jugos con leche:Dulce de Leche",
    name: "Dulce de Leche",
    category: "Jugos con leche",
    tag: "500 / 700 ml",
    description: "Vaso 500ml Bs 25 · 700ml Bs 30. Con leche.",
    price: 25.0,
    colorway: "honey",
    imageUrl: "/images/drinks/jugos-con-leche-dulce-de-leche.jpg",
    isNew: false,
    sortOrder: 6,
  },
  {
    key: "Jugos con leche:Durazno",
    name: "Durazno",
    category: "Jugos con leche",
    tag: "500 / 700 ml",
    description: "Vaso 500ml Bs 25 · 700ml Bs 30. Con leche.",
    price: 25.0,
    colorway: "honey",
    imageUrl: "/images/drinks/jugos-con-leche-durazno.jpg",
    isNew: false,
    sortOrder: 7,
  },
  {
    key: "Jugos con leche:Frutilla",
    name: "Frutilla",
    category: "Jugos con leche",
    tag: "500 / 700 ml",
    description: "Vaso 500ml Bs 25 · 700ml Bs 30. Con leche.",
    price: 25.0,
    colorway: "honey",
    imageUrl: "/images/drinks/jugos-con-leche-frutilla.jpg",
    isNew: false,
    sortOrder: 8,
  },
  {
    key: "Jugos con leche:Frutos Rojos",
    name: "Frutos Rojos",
    category: "Jugos con leche",
    tag: "500 / 700 ml",
    description: "Vaso 500ml Bs 25 · 700ml Bs 30. Con leche.",
    price: 25.0,
    colorway: "honey",
    imageUrl: "/images/drinks/jugos-con-leche-frutos-rojos.jpg",
    isNew: false,
    sortOrder: 9,
  },
  {
    key: "Jugos con leche:Mango",
    name: "Mango",
    category: "Jugos con leche",
    tag: "500 / 700 ml",
    description: "Vaso 500ml Bs 25 · 700ml Bs 30. Con leche.",
    price: 25.0,
    colorway: "honey",
    imageUrl: "/images/drinks/jugos-con-leche-mango.jpg",
    isNew: false,
    sortOrder: 10,
  },
  {
    key: "Jugos con leche:Mango con Maracuyá",
    name: "Mango con Maracuyá",
    category: "Jugos con leche",
    tag: "500 / 700 ml",
    description: "Vaso 500ml Bs 25 · 700ml Bs 30. Con leche.",
    price: 25.0,
    colorway: "honey",
    imageUrl: "/images/drinks/jugos-con-leche-mango-con-maracuya.jpg",
    isNew: false,
    sortOrder: 11,
  },
  {
    key: "Jugos con leche:Menta",
    name: "Menta",
    category: "Jugos con leche",
    tag: "500 / 700 ml",
    description: "Vaso 500ml Bs 25 · 700ml Bs 30. Con leche.",
    price: 25.0,
    colorway: "honey",
    imageUrl: "/images/drinks/jugos-con-leche-menta.jpg",
    isNew: false,
    sortOrder: 12,
  },
  {
    key: "Jugos con leche:Vainilla Cielo",
    name: "Vainilla Cielo",
    category: "Jugos con leche",
    tag: "500 / 700 ml",
    description: "Vaso 500ml Bs 25 · 700ml Bs 30. Con leche.",
    price: 25.0,
    colorway: "honey",
    imageUrl: "/images/drinks/jugos-con-leche-vainilla-cielo.jpg",
    isNew: false,
    sortOrder: 13,
  },
  {
    key: "Jugos con agua:Acerola",
    name: "Acerola",
    category: "Jugos con agua",
    tag: "500 / 700 ml",
    description: "Vaso 500ml Bs 25 · 700ml Bs 30. Con agua.",
    price: 25.0,
    colorway: "honey",
    imageUrl: "/images/drinks/jugos-con-agua-acerola.jpg",
    isNew: false,
    sortOrder: 14,
  },
  {
    key: "Jugos con agua:Achachairú",
    name: "Achachairú",
    category: "Jugos con agua",
    tag: "500 / 700 ml",
    description: "Vaso 500ml Bs 25 · 700ml Bs 30. Con agua.",
    price: 25.0,
    colorway: "honey",
    imageUrl: "/images/drinks/jugos-con-agua-achachairu.jpg",
    isNew: false,
    sortOrder: 15,
  },
  {
    key: "Jugos con agua:Coco",
    name: "Coco",
    category: "Jugos con agua",
    tag: "500 / 700 ml",
    description: "Vaso 500ml Bs 25 · 700ml Bs 30. Con agua.",
    price: 25.0,
    colorway: "honey",
    imageUrl: "/images/drinks/jugos-con-agua-coco.jpg",
    isNew: false,
    sortOrder: 16,
  },
  {
    key: "Jugos con agua:Durazno",
    name: "Durazno",
    category: "Jugos con agua",
    tag: "500 / 700 ml",
    description: "Vaso 500ml Bs 25 · 700ml Bs 30. Con agua.",
    price: 25.0,
    colorway: "honey",
    imageUrl: "/images/drinks/jugos-con-agua-durazno.jpg",
    isNew: false,
    sortOrder: 17,
  },
  {
    key: "Jugos con agua:Frutilla",
    name: "Frutilla",
    category: "Jugos con agua",
    tag: "500 / 700 ml",
    description: "Vaso 500ml Bs 25 · 700ml Bs 30. Con agua.",
    price: 25.0,
    colorway: "honey",
    imageUrl: "/images/drinks/jugos-con-agua-frutilla.jpg",
    isNew: false,
    sortOrder: 18,
  },
  {
    key: "Jugos con agua:Frutos Rojos",
    name: "Frutos Rojos",
    category: "Jugos con agua",
    tag: "500 / 700 ml",
    description: "Vaso 500ml Bs 25 · 700ml Bs 30. Con agua.",
    price: 25.0,
    colorway: "honey",
    imageUrl: "/images/drinks/jugos-con-agua-frutos-rojos.jpg",
    isNew: false,
    sortOrder: 19,
  },
  {
    key: "Jugos con agua:Frutos Rojos con Durazno",
    name: "Frutos Rojos con Durazno",
    category: "Jugos con agua",
    tag: "500 / 700 ml",
    description: "Vaso 500ml Bs 25 · 700ml Bs 30. Con agua.",
    price: 25.0,
    colorway: "honey",
    imageUrl: "/images/drinks/jugos-con-agua-frutos-rojos-con-durazno.jpg",
    isNew: false,
    sortOrder: 20,
  },
  {
    key: "Jugos con agua:Mango con Maracuyá",
    name: "Mango con Maracuyá",
    category: "Jugos con agua",
    tag: "500 / 700 ml",
    description: "Vaso 500ml Bs 25 · 700ml Bs 30. Con agua.",
    price: 25.0,
    colorway: "honey",
    imageUrl: "/images/drinks/jugos-con-agua-mango-con-maracuya.jpg",
    isNew: false,
    sortOrder: 21,
  },
  {
    key: "Jugos con agua:Maracuyá",
    name: "Maracuyá",
    category: "Jugos con agua",
    tag: "500 / 700 ml",
    description: "Vaso 500ml Bs 25 · 700ml Bs 30. Con agua.",
    price: 25.0,
    colorway: "honey",
    imageUrl: "/images/drinks/jugos-con-agua-maracuya.jpg",
    isNew: false,
    sortOrder: 22,
  },
  {
    key: "Jugos con agua:Maracuyá con Frutilla",
    name: "Maracuyá con Frutilla",
    category: "Jugos con agua",
    tag: "500 / 700 ml",
    description: "Vaso 500ml Bs 25 · 700ml Bs 30. Con agua.",
    price: 25.0,
    colorway: "honey",
    imageUrl: "/images/drinks/jugos-con-agua-maracuya-con-frutilla.jpg",
    isNew: false,
    sortOrder: 23,
  },
  {
    key: "Jugos con agua:Matcha Ice",
    name: "Matcha Ice",
    category: "Jugos con agua",
    tag: "500 / 700 ml",
    description: "Vaso 500ml Bs 25 · 700ml Bs 35. Con agua.",
    price: 25.0,
    colorway: "honey",
    imageUrl: "/images/drinks/jugos-con-agua-matcha-ice.jpg",
    isNew: false,
    sortOrder: 24,
  },
  {
    key: "Jugos con agua:Piña",
    name: "Piña",
    category: "Jugos con agua",
    tag: "500 / 700 ml",
    description: "Vaso 500ml Bs 25 · 700ml Bs 30. Con agua.",
    price: 25.0,
    colorway: "honey",
    imageUrl: "/images/drinks/jugos-con-agua-pina.jpg",
    isNew: false,
    sortOrder: 25,
  },
  {
    key: "Jugos con agua:Sandía",
    name: "Sandía",
    category: "Jugos con agua",
    tag: "500 / 700 ml",
    description: "Vaso 500ml Bs 25 · 700ml Bs 30. Con agua.",
    price: 25.0,
    colorway: "honey",
    imageUrl: "/images/drinks/jugos-con-agua-sandia.jpg",
    isNew: false,
    sortOrder: 26,
  },
  {
    key: "Jugos con agua:Tamarindo",
    name: "Tamarindo",
    category: "Jugos con agua",
    tag: "500 / 700 ml",
    description: "Vaso 500ml Bs 25 · 700ml Bs 30. Con agua.",
    price: 25.0,
    colorway: "honey",
    imageUrl: "/images/drinks/jugos-con-agua-tamarindo.jpg",
    isNew: false,
    sortOrder: 27,
  },
  {
    key: "Jugos con agua:Té de Jamaica",
    name: "Té de Jamaica",
    category: "Jugos con agua",
    tag: "500 / 700 ml",
    description: "Vaso 500ml Bs 25 · 700ml Bs 30. Con agua.",
    price: 25.0,
    colorway: "honey",
    imageUrl: "/images/drinks/jugos-con-agua-te-de-jamaica.jpg",
    isNew: false,
    sortOrder: 28,
  },
  {
    key: "Jugos con agua:Té Tradicional",
    name: "Té Tradicional",
    category: "Jugos con agua",
    tag: "500 / 700 ml",
    description: "Vaso 500ml Bs 30 · 700ml Bs 35. Con agua.",
    price: 30.0,
    colorway: "honey",
    imageUrl: "/images/drinks/jugos-con-agua-te-tradicional.jpg",
    isNew: false,
    sortOrder: 29,
  },
  {
    key: "Especiales con leche:Blueberry",
    name: "Blueberry",
    category: "Especiales con leche",
    tag: "500 / 700 ml",
    description: "Vaso 500ml Bs 30 · 700ml Bs 35. Especial.",
    price: 30.0,
    colorway: "honey",
    imageUrl: "/images/drinks/especiales-con-leche-blueberry.jpg",
    isNew: true,
    sortOrder: 30,
  },
  {
    key: "Especiales con leche:Bom Bom",
    name: "Bom Bom",
    category: "Especiales con leche",
    tag: "500 / 700 ml",
    description: "Vaso 500ml Bs 30 · 700ml Bs 40. Especial.",
    price: 30.0,
    colorway: "honey",
    imageUrl: "/images/drinks/especiales-con-leche-bom-bom.jpg",
    isNew: true,
    sortOrder: 31,
  },
  {
    key: "Especiales con leche:Café con Caramelo",
    name: "Café con Caramelo",
    category: "Especiales con leche",
    tag: "500 / 700 ml",
    description: "Vaso 500ml Bs 30 · 700ml Bs 35. Especial.",
    price: 30.0,
    colorway: "honey",
    imageUrl: "/images/drinks/especiales-con-leche-cafe-con-caramelo.jpg",
    isNew: true,
    sortOrder: 32,
  },
  {
    key: "Especiales con leche:Chocolate con Leche Condensada",
    name: "Chocolate con Leche Condensada",
    category: "Especiales con leche",
    tag: "500 / 700 ml",
    description: "Vaso 500ml Bs 30 · 700ml Bs 40. Especial.",
    price: 30.0,
    colorway: "honey",
    imageUrl: "/images/drinks/especiales-con-leche-chocolate-con-leche-condensada.jpg",
    isNew: false,
    sortOrder: 33,
  },
  {
    key: "Especiales con leche:Matcha Latte",
    name: "Matcha Latte",
    category: "Especiales con leche",
    tag: "500 / 700 ml",
    description: "Vaso 500ml Bs 30 · 700ml Bs 35. Especial.",
    price: 30.0,
    colorway: "honey",
    imageUrl: "/images/drinks/especiales-con-leche-matcha-latte.jpg",
    isNew: false,
    sortOrder: 34,
  },
  {
    key: "Especiales con leche:Moca",
    name: "Moca",
    category: "Especiales con leche",
    tag: "500 / 700 ml",
    description: "Vaso 500ml Bs 30 · 700ml Bs 35. Especial.",
    price: 30.0,
    colorway: "honey",
    imageUrl: "/images/drinks/especiales-con-leche-moca.jpg",
    isNew: false,
    sortOrder: 35,
  },
  {
    key: "Especiales con leche:Mousse de Maracuyá",
    name: "Mousse de Maracuyá",
    category: "Especiales con leche",
    tag: "500 / 700 ml",
    description: "Vaso 500ml Bs 30 · 700ml Bs 35. Especial.",
    price: 30.0,
    colorway: "honey",
    imageUrl: "/images/drinks/especiales-con-leche-mousse-de-maracuya.jpg",
    isNew: false,
    sortOrder: 36,
  },
  {
    key: "Especiales con leche:Oreo",
    name: "Oreo",
    category: "Especiales con leche",
    tag: "500 / 700 ml",
    description: "Vaso 500ml Bs 30 · 700ml Bs 35. Especial.",
    price: 30.0,
    colorway: "honey",
    imageUrl: "/images/drinks/especiales-con-leche-oreo.jpg",
    isNew: false,
    sortOrder: 37,
  },
  {
    key: "Especiales con leche:Pie de Limón",
    name: "Pie de Limón",
    category: "Especiales con leche",
    tag: "500 / 700 ml",
    description: "Vaso 500ml Bs 30 · 700ml Bs 35. Especial.",
    price: 30.0,
    colorway: "honey",
    imageUrl: "/images/drinks/especiales-con-leche-pie-de-limon.jpg",
    isNew: false,
    sortOrder: 38,
  },
  {
    key: "Especiales con leche:Pitahaya Roja Dulce",
    name: "Pitahaya Roja Dulce",
    category: "Especiales con leche",
    tag: "500 / 700 ml",
    description: "Vaso 500ml Bs 30 · 700ml Bs 35. Especial.",
    price: 30.0,
    colorway: "honey",
    imageUrl: "/images/drinks/especiales-con-leche-pitahaya-roja-dulce.jpg",
    isNew: false,
    sortOrder: 39,
  },
  {
    key: "Especiales con leche:Pitahaya Blanca Refrescante",
    name: "Pitahaya Blanca Refrescante",
    category: "Especiales con leche",
    tag: "500 / 700 ml",
    description: "Vaso 500ml Bs 30 · 700ml Bs 35. Especial.",
    price: 30.0,
    colorway: "honey",
    imageUrl: "/images/drinks/especiales-con-leche-pitahaya-blanca-refrescante.jpg",
    isNew: false,
    sortOrder: 40,
  },
  {
    key: "Especiales con leche:Tiramisú",
    name: "Tiramisú",
    category: "Especiales con leche",
    tag: "500 / 700 ml",
    description: "Vaso 500ml Bs 30 · 700ml Bs 35. Especial.",
    price: 30.0,
    colorway: "honey",
    imageUrl: "/images/drinks/especiales-con-leche-tiramisu.jpg",
    isNew: false,
    sortOrder: 41,
  },
  {
    key: "Especiales con leche:Uva",
    name: "Uva",
    category: "Especiales con leche",
    tag: "500 / 700 ml",
    description: "Vaso 500ml Bs 30 · 700ml Bs 35. Especial.",
    price: 30.0,
    colorway: "honey",
    imageUrl: "/images/drinks/especiales-con-leche-uva.jpg",
    isNew: false,
    sortOrder: 42,
  },
  {
    key: "Especiales con leche:Açaí",
    name: "Açaí",
    category: "Especiales con leche",
    tag: "500 / 700 ml",
    description: "Vaso 500ml Bs 35 · 700ml Bs 40. Especial.",
    price: 35.0,
    colorway: "honey",
    imageUrl: "/images/drinks/especiales-con-leche-acai.jpg",
    isNew: false,
    sortOrder: 43,
  },
  {
    key: "Especiales con leche:Matcha con Frutilla",
    name: "Matcha con Frutilla",
    category: "Especiales con leche",
    tag: "500 / 700 ml",
    description: "Vaso 500ml Bs 35 · 700ml Bs 40. Especial.",
    price: 35.0,
    colorway: "honey",
    imageUrl: "/images/drinks/especiales-con-leche-matcha-con-frutilla.jpg",
    isNew: false,
    sortOrder: 44,
  },
  {
    key: "Especiales con leche:Matcha con Oreo",
    name: "Matcha con Oreo",
    category: "Especiales con leche",
    tag: "500 / 700 ml",
    description: "Vaso 500ml Bs 35 · 700ml Bs 40. Especial.",
    price: 35.0,
    colorway: "honey",
    imageUrl: "/images/drinks/especiales-con-leche-matcha-con-oreo.jpg",
    isNew: false,
    sortOrder: 45,
  },
  {
    key: "Especiales con leche:Taro",
    name: "Taro",
    category: "Especiales con leche",
    tag: "500 / 700 ml",
    description: "Vaso 500ml Bs 35 · 700ml Bs 40. Especial.",
    price: 35.0,
    colorway: "honey",
    imageUrl: "/images/drinks/especiales-con-leche-taro.jpg",
    isNew: false,
    sortOrder: 46,
  },
  {
    key: "Especiales con leche:Té Chai",
    name: "Té Chai",
    category: "Especiales con leche",
    tag: "500 / 700 ml",
    description: "Vaso 500ml Bs 35 · 700ml Bs 40. Especial.",
    price: 35.0,
    colorway: "honey",
    imageUrl: "/images/drinks/especiales-con-leche-te-chai.jpg",
    isNew: false,
    sortOrder: 47,
  },
  {
    key: "Frappés:Banana",
    name: "Banana",
    category: "Frappés",
    tag: "500 ml",
    description: "Vaso 500ml. 500ml con leche.",
    price: 30.0,
    colorway: "honey",
    imageUrl: "/images/drinks/frappes-banana.jpg",
    isNew: false,
    sortOrder: 48,
  },
  {
    key: "Frappés:Café",
    name: "Café",
    category: "Frappés",
    tag: "500 ml",
    description: "Vaso 500ml. 500ml con leche.",
    price: 30.0,
    colorway: "honey",
    imageUrl: "/images/drinks/frappes-cafe.jpg",
    isNew: false,
    sortOrder: 49,
  },
  {
    key: "Frappés:Coco",
    name: "Coco",
    category: "Frappés",
    tag: "500 ml",
    description: "Vaso 500ml. 500ml con leche o agua.",
    price: 30.0,
    colorway: "honey",
    imageUrl: "/images/drinks/frappes-coco.jpg",
    isNew: false,
    sortOrder: 50,
  },
  {
    key: "Frappés:Chocolate",
    name: "Chocolate",
    category: "Frappés",
    tag: "500 ml",
    description: "Vaso 500ml. 500ml con leche.",
    price: 30.0,
    colorway: "honey",
    imageUrl: "/images/drinks/frappes-chocolate.jpg",
    isNew: false,
    sortOrder: 51,
  },
  {
    key: "Frappés:Dulce de Leche",
    name: "Dulce de Leche",
    category: "Frappés",
    tag: "500 ml",
    description: "Vaso 500ml. 500ml con leche.",
    price: 30.0,
    colorway: "honey",
    imageUrl: "/images/drinks/frappes-dulce-de-leche.jpg",
    isNew: false,
    sortOrder: 52,
  },
  {
    key: "Frappés:Durazno",
    name: "Durazno",
    category: "Frappés",
    tag: "500 ml",
    description: "Vaso 500ml. 500ml con leche o agua.",
    price: 30.0,
    colorway: "honey",
    imageUrl: "/images/drinks/frappes-durazno.jpg",
    isNew: false,
    sortOrder: 53,
  },
  {
    key: "Frappés:Frutilla",
    name: "Frutilla",
    category: "Frappés",
    tag: "500 ml",
    description: "Vaso 500ml. 500ml con leche o agua.",
    price: 30.0,
    colorway: "honey",
    imageUrl: "/images/drinks/frappes-frutilla.jpg",
    isNew: false,
    sortOrder: 54,
  },
  {
    key: "Frappés:Frutos Rojos",
    name: "Frutos Rojos",
    category: "Frappés",
    tag: "500 ml",
    description: "Vaso 500ml. 500ml con leche o agua.",
    price: 30.0,
    colorway: "honey",
    imageUrl: "/images/drinks/frappes-frutos-rojos.jpg",
    isNew: false,
    sortOrder: 55,
  },
  {
    key: "Frappés:Mango",
    name: "Mango",
    category: "Frappés",
    tag: "500 ml",
    description: "Vaso 500ml. 500ml con leche.",
    price: 30.0,
    colorway: "honey",
    imageUrl: "/images/drinks/frappes-mango.jpg",
    isNew: false,
    sortOrder: 56,
  },
  {
    key: "Frappés:Maracuyá",
    name: "Maracuyá",
    category: "Frappés",
    tag: "500 ml",
    description: "Vaso 500ml. 500ml con leche o agua.",
    price: 30.0,
    colorway: "honey",
    imageUrl: "/images/drinks/frappes-maracuya.jpg",
    isNew: false,
    sortOrder: 57,
  },
  {
    key: "Frappés:Menta",
    name: "Menta",
    category: "Frappés",
    tag: "500 ml",
    description: "Vaso 500ml. 500ml con leche.",
    price: 30.0,
    colorway: "honey",
    imageUrl: "/images/drinks/frappes-menta.jpg",
    isNew: false,
    sortOrder: 58,
  },
  {
    key: "Frappés:Moca",
    name: "Moca",
    category: "Frappés",
    tag: "500 ml",
    description: "Vaso 500ml. 500ml con leche.",
    price: 30.0,
    colorway: "honey",
    imageUrl: "/images/drinks/frappes-moca.jpg",
    isNew: false,
    sortOrder: 59,
  },
  {
    key: "Frappés:Oreo",
    name: "Oreo",
    category: "Frappés",
    tag: "500 ml",
    description: "Vaso 500ml. 500ml con leche.",
    price: 30.0,
    colorway: "honey",
    imageUrl: "/images/drinks/frappes-oreo.jpg",
    isNew: false,
    sortOrder: 60,
  },
  {
    key: "Frappés:Pie de Limón",
    name: "Pie de Limón",
    category: "Frappés",
    tag: "500 ml",
    description: "Vaso 500ml. 500ml con leche.",
    price: 30.0,
    colorway: "honey",
    imageUrl: "/images/drinks/frappes-pie-de-limon.jpg",
    isNew: false,
    sortOrder: 61,
  },
  {
    key: "Frappés:Piña",
    name: "Piña",
    category: "Frappés",
    tag: "500 ml",
    description: "Vaso 500ml. 500ml con leche o agua.",
    price: 30.0,
    colorway: "honey",
    imageUrl: "/images/drinks/frappes-pina.jpg",
    isNew: false,
    sortOrder: 62,
  },
  {
    key: "Frappés:Vainilla",
    name: "Vainilla",
    category: "Frappés",
    tag: "500 ml",
    description: "Vaso 500ml. 500ml con leche.",
    price: 30.0,
    colorway: "honey",
    imageUrl: "/images/drinks/frappes-vainilla.jpg",
    isNew: false,
    sortOrder: 63,
  },
  {
    key: "Frappés:Açaí",
    name: "Açaí",
    category: "Frappés",
    tag: "500 ml",
    description: "Vaso 500ml. 500ml con leche.",
    price: 35.0,
    colorway: "honey",
    imageUrl: "/images/drinks/frappes-acai.jpg",
    isNew: true,
    sortOrder: 64,
  },
  {
    key: "Frappés:Blueberry",
    name: "Blueberry",
    category: "Frappés",
    tag: "500 ml",
    description: "Vaso 500ml. 500ml con leche.",
    price: 35.0,
    colorway: "honey",
    imageUrl: "/images/drinks/frappes-blueberry.jpg",
    isNew: true,
    sortOrder: 65,
  },
  {
    key: "Frappés:Mousse de Maracuyá",
    name: "Mousse de Maracuyá",
    category: "Frappés",
    tag: "500 ml",
    description: "Vaso 500ml. 500ml con leche.",
    price: 35.0,
    colorway: "honey",
    imageUrl: "/images/drinks/frappes-mousse-de-maracuya.jpg",
    isNew: false,
    sortOrder: 66,
  },
];

const toppings = [
  {
    name: "Jalea Frutilla",
    price: 5.0,
    colorway: "jelly",
    imageUrl: "/images/toppings/jalea-frutilla.jpg",
    sortOrder: 1,
  },
  {
    name: "Jalea Condensada",
    price: 5.0,
    colorway: "jelly",
    imageUrl: "/images/toppings/jalea-condensada.jpg",
    sortOrder: 2,
  },
  {
    name: "Jalea Dulce de Leche",
    price: 5.0,
    colorway: "jelly",
    imageUrl: "/images/toppings/jalea-dulce-de-leche.jpg",
    sortOrder: 3,
  },
  {
    name: "Jalea Chocolate",
    price: 5.0,
    colorway: "jelly",
    imageUrl: "/images/toppings/jalea-chocolate.jpg",
    sortOrder: 4,
  },
  {
    name: "Perlas Tradicionales",
    price: 5.0,
    colorway: "pearl",
    imageUrl: "/images/toppings/perlas-tradicionales.jpg",
    sortOrder: 5,
  },
];

function drinkId(key: string) {
  return `seed-${key}`;
}

async function main() {
  // Remove previous fictional / seed menu so only the real catalog remains.
  await prisma.orderItem.deleteMany();
  await prisma.order.deleteMany();
  await prisma.drink.deleteMany();
  await prisma.topping.deleteMany();

  for (const drink of drinks) {
    const { key, ...data } = drink;
    await prisma.drink.create({
      data: { id: drinkId(key), ...data },
    });
  }

  for (const topping of toppings) {
    await prisma.topping.create({
      data: { id: `seed-${topping.name}`, ...topping },
    });
  }

  console.log(`Seeded ${drinks.length} drinks and ${toppings.length} toppings from Mundo Bubble Tea menu.`);
}

main()
  .catch((err) => {
    console.error(err);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
